version: '3.7'
services:
  kernel_MM:
    container_name: 'kernel_MM'
    build:
      context: .
      dockerfile: Dockerfile
    image: base
    volumes:
      - ./parallel_CUDA:/parallel_CUDA
      - ./results_CUDA:/results_CUDA
      - ./images:/images
    stdin_open: true
    tty: true
    ipc: 'host'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIESA=all
      - nvcc-arch=sm_52 -v -Xcompiler="-pthread"
