version: '3.7'
services:
  kernelMM:     # To use chosen images
    container_name: 'kernelMM'
    build:
      context: .
      dockerfile: Dockerfile
    image: base
    volumes:
      - ./parallel_CUDA:/parallel_CUDA
      - ./results_CUDA:/results_CUDA
      - ./images:/images
    stdin_open: true
    tty: true
    ipc: 'host'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIESA=all
      - nvcc-arch=sm_52 -v -Xcompiler="-pthread"
      - NUM_THREAD_PER_AXIS=32  #default value

  autoKernelMM:     # To use default images
    container_name: 'autoKernelMM'
    build:
      context: .
      dockerfile: DockerfileAutoKernel
    image: base
    volumes:
      - ./parallel_CUDA:/parallel_CUDA
      - ./results_CUDA:/results_CUDA
      - ./images:/images
    stdin_open: true
    tty: true
    ipc: 'host'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIESA=all
      - nvcc-arch=sm_52 -v -Xcompiler="-pthread"
      - NUM_THREAD_PER_AXIS=32  #default value
    command: /autoKernelProcessing.sh

  evaluateSpeedup:      # After produced timings.csv
    container_name: 'evaluateSpeedup'
    build:
      context: .
      dockerfile: DockerfileForSpeedup
    image: base
    volumes:
      - ./results_CUDA:/results_CUDA
    stdin_open: true
    tty: true
    ipc: 'host'
    command: python3 /results_CUDA/evaluate_speedup.py
